import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const config = [
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  {
    // Generated by Payload; never hand-edited.
    ignores: [".next/", "node_modules/", "desert-peak-brand/", "src/payload-types.ts", "app/(payload)/admin/importMap.js", "src/migrations/"],
  },
];

export default config;
