/* GENERATED by scripts/build-web.ts from brand/logos/favicon.svg. Do not edit; the geometry is the locked identity. */
import type { SVGProps } from "react";

/** Favicon: inline SVG, scales with width/height or CSS; colours are token values. */
export function Favicon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} viewBox="0 0 64 64" role="img" aria-labelledby="dp-favicon-title"><title id="dp-favicon-title">Desert Peak Insurance</title><polygon fill="#923D28" points="0,10 35.44,10 33.25,24 0,24"/><polygon fill="#923D28" points="0,30 32.31,30 30.12,44 0,44"/><polygon fill="#923D28" points="0,50 29.19,50 27,64 0,64"/><polygon fill="#923D28" points="41,0 64,0 64,14 38.81,14"/><polygon fill="#923D28" points="37.88,20 64,20 64,34 35.69,34"/><polygon fill="#923D28" points="34.75,40 64,40 64,54 32.56,54"/></svg>
  );
}
