/**
 * The accessibility gate. Fails (exit 1) when any legitimate foreground/background pairing in the
 * semantic layer misses WCAG 2.2: body text < 4.5:1, large text or UI boundaries < 3:1, focus ring
 * < 3:1 against either adjacent surface. Also verifies the state colours stay distinguishable under
 * protanopia and deuteranopia simulation by something other than hue, and that every hex found in
 * brand/logos/*.svg is a token value.
 *
 * Writes brand/CONTRAST-REPORT.md. Usage: node scripts/audit-contrast.ts
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  BRAND, CVD_MIN_DELTA_E, CVD_MIN_DELTA_L, INFO_SET, PAIRINGS, STATE_SET, aliasChainEnd, contrast, deltaE, flatten, fmt, lightness, loadTokens, simulate, toHex,
} from "./lib.ts";

const tree = loadTokens();
const flat = flatten(tree);
const version = (tree.$extensions as any)?.["com.desertpeak"]?.version ?? "0.0.0";

const primHex = new Map<string, string>();
for (const [p, t] of flat) if (p.startsWith("color.")) primHex.set(p, toHex(t.$value as string));
const sem = new Map<string, { hex: string; ref: string }>();
for (const [p, t] of flat) if (p.startsWith("semantic.color.")) {
  const ref = aliasChainEnd(t.$value, flat)!;
  sem.set(p.replace("semantic.color.", ""), { hex: primHex.get(ref)!, ref: ref.replace("color.", "") });
}
const hexOf = (role: string) => { const s = sem.get(role); if (!s) throw new Error(`Unknown semantic role: ${role}`); return s.hex; };

let failures = 0;
const md: string[] = [];
md.push(`# Contrast report`, ``, `Generated by \`scripts/audit-contrast.ts\` from \`design-tokens.json\` v${version}. WCAG 2.2 contrast ratios computed from sRGB relative luminance. This file is a build artefact; if it says FAIL, the token set is not done.`, ``);

// ---------------------------------------------------------------------------
// 1. Pairings
// ---------------------------------------------------------------------------
md.push(`## Semantic pairings`, ``, `| Foreground | Background | Ratio | Requirement | Result | Use |`, `|---|---|---:|---:|---|---|`);
for (const p of PAIRINGS) {
  const r = contrast(hexOf(p.fg), hexOf(p.bg));
  let result = "n/a (decorative)";
  if (p.min > 0) {
    const ok = r >= p.min;
    if (!ok) failures++;
    result = ok ? "pass" : "**FAIL**";
  }
  md.push(`| \`${p.fg}\` ${hexOf(p.fg)} | \`${p.bg}\` ${hexOf(p.bg)} | ${fmt(r)} | ${p.min ? p.min + ":1" : "—"} | ${result} | ${p.note} |`);
}
md.push(``, `Requirements: 4.5:1 for text below 24px (18.66px bold); 3:1 for large text, UI component boundaries and focus indicators (WCAG 1.4.3, 1.4.11, 2.4.13). Decorative rows are reported for information and carry no requirement; the guide forbids using them to convey meaning.`, ``);

// ---------------------------------------------------------------------------
// 2. Colour-vision deficiency
// ---------------------------------------------------------------------------
md.push(`## State colours under colour-vision deficiency`, ``, `Simulation: Machado, Oliveira & Fernandes (2009), severity 1.0, applied in linear sRGB (the model Chrome DevTools uses). Distance is Euclidean in OKLab (≈0.02 is a just-noticeable difference). Every pair of state colours must keep ΔE ≥ ${CVD_MIN_DELTA_E} under normal vision, protanopia and deuteranopia, **and** differ in OKLab lightness by ≥ ${CVD_MIN_DELTA_L} so that hue is never the only cue. Status UI must also carry an icon and a word; tokens cannot enforce that, the guide does.`, ``);
md.push(`| Role | Normal | Protanopia | Deuteranopia | L |`, `|---|---|---|---|---:|`);
const roles = [...STATE_SET];
for (const r of roles) md.push(`| \`${r}\` | ${hexOf(r)} | ${simulate(hexOf(r), "protan")} | ${simulate(hexOf(r), "deutan")} | ${lightness(hexOf(r)).toFixed(3)} |`);
md.push(``, `| Pair | ΔE normal | ΔE protan | ΔE deutan | ΔL | Result |`, `|---|---:|---:|---:|---:|---|`);
for (let i = 0; i < roles.length; i++) for (let j = i + 1; j < roles.length; j++) {
  const a = hexOf(roles[i]), b = hexOf(roles[j]);
  const dN = deltaE(a, b), dP = deltaE(simulate(a, "protan"), simulate(b, "protan")), dD = deltaE(simulate(a, "deutan"), simulate(b, "deutan"));
  const dL = Math.abs(lightness(a) - lightness(b));
  const ok = Math.min(dN, dP, dD) >= CVD_MIN_DELTA_E && dL >= CVD_MIN_DELTA_L;
  if (!ok) failures++;
  md.push(`| \`${roles[i]}\` / \`${roles[j]}\` | ${dN.toFixed(3)} | ${dP.toFixed(3)} | ${dD.toFixed(3)} | ${dL.toFixed(3)} | ${ok ? "pass" : "**FAIL**"} |`);
}
md.push(``, `Brand against the states, for information. Brand is not a status colour; it is listed so the overlap is on the record (brand and notice share a lightness and converge under deuteranopia, which is why notice never appears without its icon and leading word, and why brand is never used to signal a state).`, ``, `| Pair | ΔE normal | ΔE protan | ΔE deutan | ΔL |`, `|---|---:|---:|---:|---:|`);
for (const i of INFO_SET) for (const r of roles) {
  const a = hexOf(i), b = hexOf(r);
  md.push(`| \`${i}\` / \`${r}\` | ${deltaE(a, b).toFixed(3)} | ${deltaE(simulate(a, "protan"), simulate(b, "protan")).toFixed(3)} | ${deltaE(simulate(a, "deutan"), simulate(b, "deutan")).toFixed(3)} | ${Math.abs(lightness(a) - lightness(b)).toFixed(3)} |`);
}
md.push(``);
// Borders of callouts: informational (surfaces are near-white and are expected to converge; the border + icon carry the state)
md.push(`Callout borders (\`*-border\`), for information. Tinted callout surfaces are deliberately close to one another; the border, icon and label carry the state.`, ``, `| Pair | ΔE normal | ΔE protan | ΔE deutan | ΔL |`, `|---|---:|---:|---:|---:|`);
const borders = ["positive-border", "notice-border", "critical-border"];
for (let i = 0; i < borders.length; i++) for (let j = i + 1; j < borders.length; j++) {
  const a = hexOf(borders[i]), b = hexOf(borders[j]);
  md.push(`| \`${borders[i]}\` / \`${borders[j]}\` | ${deltaE(a, b).toFixed(3)} | ${deltaE(simulate(a, "protan"), simulate(b, "protan")).toFixed(3)} | ${deltaE(simulate(a, "deutan"), simulate(b, "deutan")).toFixed(3)} | ${Math.abs(lightness(a) - lightness(b)).toFixed(3)} |`);
}
md.push(``);

// ---------------------------------------------------------------------------
// 3. Logo assets use token colours only
// ---------------------------------------------------------------------------
md.push(`## Logo assets`, ``, `Every hex literal in \`brand/logos/*.svg\` must be a token value (logos are the one place a hex is allowed to live outside the token file, and only because SVG cannot read CSS variables in email or print).`, ``);
const logosDir = join(BRAND, "logos");
const hexToPrim = new Map([...primHex].map(([p, h]) => [h, p.replace("color.", "")]));
if (!existsSync(logosDir)) { md.push(`_No logos directory yet._`, ``); }
else {
  md.push(`| File | Hex | Token |`, `|---|---|---|`);
  for (const f of readdirSync(logosDir).filter((f) => f.endsWith(".svg")).sort()) {
    const found = [...new Set((readFileSync(join(logosDir, f), "utf8").match(/#[0-9a-fA-F]{6}\b/g) ?? []).map((h) => h.toUpperCase()))];
    if (!found.length) { md.push(`| ${f} | — (currentColor) | — |`); continue; }
    for (const h of found) {
      const t = hexToPrim.get(h);
      if (!t) failures++;
      md.push(`| ${f} | ${h} | ${t ? `\`${t}\`` : "**FAIL: not a token**"} |`);
    }
  }
  md.push(``);
}

md.push(`## Result`, ``, failures ? `**${failures} failure(s). The token set is not done.**` : `All checks pass.`, ``);
writeFileSync(join(BRAND, "CONTRAST-REPORT.md"), md.join("\n"));
console.log(failures ? `audit-contrast: ${failures} FAILURE(S) — see brand/CONTRAST-REPORT.md` : "audit-contrast: all checks pass — brand/CONTRAST-REPORT.md");
process.exit(failures ? 1 : 0);
