/**
 * Composes COLLATERAL-INVENTORY.md from every surface's INVENTORY.json (written by its generator)
 * plus the identity assets this stage consumes. Usage: node scripts/build-inventory.ts
 */
import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { ROOT, TODAY, pngSize, type InventoryRow } from "./collateral/lib.ts";

const SURFACES: { dir: string; title: string; script: string; stage: string }[] = [
  { dir: "social", title: "Social media kit", script: "scripts/build-social.ts", stage: "5.1" },
  { dir: "email", title: "Email signatures", script: "scripts/build-signatures.ts", stage: "5.2" },
  { dir: "decks", title: "Presentation decks", script: "scripts/build-decks.ts", stage: "5.3" },
  { dir: "web", title: "Website and UI assets", script: "scripts/build-web.ts", stage: "5.4" },
  { dir: "print", title: "Business cards", script: "scripts/build-print.ts + scripts/preflight-print.ts", stage: "5.5" },
  { dir: "showcase", title: "Showcase", script: "scripts/build-showcase.ts", stage: "5.6" },
];
const md: string[] = [];
md.push(`# Collateral inventory`, ``, `Generated ${TODAY} by \`scripts/build-inventory.ts\` from each surface's \`INVENTORY.json\`. Every asset below is regenerated by \`pnpm build:collateral\` from \`brand/design-tokens.json\`, \`brand/logos/\`, \`people.json\`, \`collateral.config.json\` and \`content/*.json\`. Platform specifications change; the "checked" column is the date the spec was read, and the URL is where. Re-check before a campaign.`, ``);
md.push(`## Identity inputs (locked, Stage 2–3)`, ``, `| Asset | Dimensions | Source | Lock |`, `|---|---|---|---|`);
for (const f of ["mark.svg", "favicon.svg", "logo-horizontal.svg", "logo-stacked.svg", "logo-reversed.svg", "logo-mono.svg", "wordmark.svg"]) {
  const p = join(ROOT, "brand", "logos", f);
  const vb = readFileSync(p, "utf8").match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/)!;
  md.push(`| brand/logos/${f} | viewBox ${vb[1]}×${vb[2]} | hand-authored (Stage 3) | sha256 in brand/logos/MANIFEST.sha256, checked by verify-token-lock |`);
}
md.push(`| brand/design-tokens.json | 67 primitives, 31 semantic roles | Stage 2 | the only source of colour, type, space |`, ``);
let total = 0;
for (const s of SURFACES) {
  const p = join(ROOT, s.dir, "INVENTORY.json");
  md.push(`## ${s.stage} ${s.title}`, ``);
  if (!existsSync(p)) { md.push(`_Not built yet (${s.script})._`, ``); continue; }
  const rows: InventoryRow[] = JSON.parse(readFileSync(p, "utf8")).rows;
  md.push(`Generator: \`${s.script}\` · ${rows.length} assets`, ``, `| Asset | Dimensions | Source script | Spec verified against | Checked | Notes |`, `|---|---|---|---|---|---|`);
  for (const r of rows) {
    const spec = r.specUrl ? `[${r.spec ?? "spec"}](${r.specUrl})` : (r.spec ?? "—");
    let dims = r.dimensions;
    const abs = join(ROOT, r.asset);
    if ((!dims || dims === "?") && existsSync(abs) && abs.endsWith(".png")) { const z = pngSize(abs); dims = `${z.w}×${z.h}`; }
    const bytes = existsSync(abs) ? ` (${(statSync(abs).size / 1024).toFixed(1)} KB)` : " (missing)";
    md.push(`| ${r.asset}${bytes} | ${dims ?? "—"} | ${r.source} | ${spec} | ${r.checked ?? "—"} | ${r.notes ?? ""} |`);
    total++;
  }
  md.push(``);
}
md.push(`## Totals`, ``, `${total} generated assets across ${SURFACES.filter((s) => existsSync(join(ROOT, s.dir, "INVENTORY.json"))).length} surfaces.`, ``);
md.push(`## Gates`, ``, "```", "pnpm verify:token-lock        # zero off-token colours, fonts, or altered marks", "pnpm build:collateral         # regenerates every asset from tokens + people.json", "pnpm audit:contrast           # the token set every template draws from", "pnpm check:banned-phrases     # every text layer in social, decks, OG, email", "pnpm check:medicare           # every Medicare-flagged asset carries TPMO", "pnpm preflight:print          # business-card PDFs pass", "pnpm build:showcase           # showcase/index.html renders from real assets", "```", ``);
import("node:fs").then((fs) => { fs.writeFileSync(join(ROOT, "COLLATERAL-INVENTORY.md"), md.join("\n")); console.log(`build-inventory: ${total} assets -> COLLATERAL-INVENTORY.md`); });
