import type { ProductDraft } from "../types.mts";

export const draft: ProductDraft = {
  summary: "A contract with an insurer that turns a sum of money into a stream of payments, now or later. The contract decides how the balance grows, when payments start, what leaving early costs and what passes to heirs; the analysis reads those terms before anything is signed.",
  intro: [
    "An annuity is an insurance contract, not a security bought on an exchange. You pay a premium, in one sum or over time, and the insurer promises to pay it back with growth on a schedule the contract fixes. The two halves are the accumulation phase, when the balance grows, and the payout phase, when the insurer sends payments for a set number of years or for as long as you live. Which half you are buying, and how long each lasts, is the first thing to read on the contract.",
    "Annuities are used for one job above others: turning savings into income that cannot be outlived. A pension does that job for the people who have one, and an annuity is the version anyone can buy. They are also used to defer tax on growth, since interest inside a deferred annuity is not taxed until it is withdrawn, and to leave a defined amount to a named beneficiary outside probate.",
    "What an annuity is not is investment advice. We are licensed to sell insurance contracts, and the analysis compares the contract terms, the floors, the surrender schedule and the insurer's financial strength against what the money is meant to do. When the answer is that the money should stay where it is, that is what we say.",
  ],
  coverageBlocks: [
    { heading: "Fixed annuities", paragraphs: ["A fixed annuity credits interest at a rate the insurer declares, locked for an initial period and then reset at the insurer's discretion above a floor written in the contract. The balance cannot go down from market movement; the trade is that the credited rate is what you get, whatever the markets do. Multi-year rate-lock contracts hold one declared rate for the whole term, which makes them behave like a bank certificate issued by an insurer, with tax deferral and without federal deposit insurance."] },
    { heading: "Fixed-indexed annuities", paragraphs: ["A fixed-indexed annuity credits interest by a formula tied to a market index, without putting the money in the index. The insurer sets a cap, a participation rate or a spread that limits how much of the index gain is credited, and a floor, usually zero, that stops losses. The formula is reset each term, so the cap you are shown at purchase is not the cap you will have in year five. Reading the crediting method is the whole job with this product; two contracts on the same index can credit very different amounts in the same year."] },
    { heading: "Immediate and deferred", paragraphs: ["An immediate annuity starts paying within a year of purchase: you hand over a sum and payments begin, sized by your age, the payout option and the interest rate environment at the time. A deferred annuity accumulates first, sometimes for many years, and converts to income later or is simply withdrawn. Deferred contracts are the ones usually shown to buyers still working; immediate contracts are the purer income tool and are usually bought at or after retirement."] },
    { heading: "Payout options", paragraphs: ["At annuitization you choose how the income is shaped. Life only pays the most per month and stops at death, whatever has been paid out. Life with period certain keeps paying a beneficiary if you die before the certain period ends. Joint and survivor continues for a spouse, at the same or a reduced amount. Each option is a trade between the size of the payment and what survives you, and the choice is usually irreversible once payments start."] },
    { heading: "Surrender periods and charges", paragraphs: ["A deferred annuity carries a surrender period, commonly several years, during which withdrawals above a stated free-withdrawal amount incur a charge that declines each year. Withdrawals of growth before the federal early-withdrawal age can also carry a tax penalty on top of income tax. The surrender schedule is where the analysis spends the most time: money you may need inside that window does not belong in the contract."] },
    { heading: "Riders and death benefits", paragraphs: ["Riders add features for a fee taken from the balance: a guaranteed minimum income benefit that sets a floor on future income regardless of performance, an enhanced death benefit for heirs, or a waiver that lifts surrender charges after a nursing-home admission or terminal diagnosis. A rider's fee is charged every year whether or not it is ever used, so each one is worth pricing against what it would cost to buy the same thing separately."] },
  ],
  covered: [
    "Interest credited by a declared rate or an index-linked formula, with a floor written in the contract",
    "Income payments for a fixed period or for life, once annuitized",
    "Tax deferral on growth until it is withdrawn",
    "A named beneficiary paid outside probate at death",
    "A free-withdrawal amount each contract year during the surrender period",
    "Continued payments to a spouse under a joint and survivor option",
  ],
  notCovered: [
    "Withdrawals above the free amount during the surrender period, which carry a charge",
    "Inflation, unless a cost-of-living rider is added",
    "Federal deposit insurance; the promise rests on the issuing insurer and the state guaranty association",
    "Index gains above the cap, participation rate or spread in an indexed contract",
    "Payments after death under a life-only option, whatever the balance was",
    "Investment advice; the contract is insurance, and we compare contracts, not portfolios",
  ],
  faqs: [
    { question: "Is an annuity an investment?", answer: ["Legally it is an insurance contract issued by a life insurer, and the fixed and fixed-indexed types we place are regulated by the state insurance departments, not by securities regulators. Variable annuities, which invest in sub-accounts and can lose value, are securities and require a different licence; we do not sell them. Whether an annuity fits alongside your other accounts is a question for your tax or financial advisor, and we will send the contract terms to that person on request."] },
    { question: "What happens to the money if I die early?", answer: ["It depends on the phase and the option. During accumulation, the death benefit, normally the account value or the premium paid less withdrawals, goes to the beneficiary. After annuitization, a life-only option ends at death, a period-certain option pays the remaining certain payments, and a joint option continues for the survivor. Naming a beneficiary keeps the money out of probate; leaving the line blank sends it to the estate."] },
    { question: "How is the payout amount decided?", answer: ["By the sum annuitized, your age, the payout option chosen and the interest rate environment when payments start. Older annuitants and shorter certain periods produce larger monthly amounts. Suppose two people each annuitize $100,000 on the same day; the one who chooses life only will receive a larger monthly payment than the one who chooses life with twenty years certain, because the insurer expects to pay for fewer years."] },
    { question: "Can I move an old annuity into a new one?", answer: ["Yes, through a 1035 exchange that keeps the tax deferral intact. Whether it is wise depends on what the old contract still charges to surrender, what the new one offers and how long a new surrender period would run. Exchanges are the transactions regulators watch most closely, and the analysis is written down so you can see why we did or did not recommend one."] },
    { question: "What does the state guaranty association do?", answer: ["Each state runs an association, funded by licensed insurers, that steps in if an issuing insurer fails, covering annuity values up to a ceiling set by that state. The ceiling is per person per insurer, and the mechanism is a backstop rather than deposit insurance; spreading large sums across insurers is the standard way to stay under it. Arizona, Nevada, Utah and Idaho each set their own figure."] },
    { question: "When is the recommendation to do nothing?", answer: ["When the money is already in a contract with no surrender charge and a competitive floor, when the funds may be needed inside a new surrender window, or when the buyer is looking for growth rather than a floor. An annuity sold to someone who needs liquidity is the wrong product however good the contract; we would rather say so than write it."] },
  ],
  relatedProducts: ["life-insurance", "whole-life-insurance", "indexed-universal-life-insurance", "term-life-insurance"],
  seo: { description: "How fixed, fixed-indexed, immediate and deferred annuities work: crediting methods, payout options, surrender periods and riders, explained by an independent agency licensed in Arizona, Nevada, Utah and Idaho." },
};
