import type { ProductDraft } from "../types.mts";

export const draft: ProductDraft = {
  summary: "Pays a share of medical bills after the deductible, up to an annual out-of-pocket maximum, through a network of providers. The plan's metal tier, network type and deductible decide what you pay each month and what you pay when you are sick; the analysis compares both.",
  intro: [
    "A health plan sets what you pay for care in three layers: the premium every month, the deductible before the plan pays much of anything, and the copays and coinsurance after that until an annual out-of-pocket maximum stops the spending. Under the Affordable Care Act every individual plan sold in the four states covers the same essential health benefits and cannot turn you down or charge you more for a health condition, so the differences between plans are in the cost layers and the network, not in whether cancer is covered.",
    "Individual and family plans are bought through the federal marketplace, through a state marketplace where a state runs one (Nevada and Idaho do; Arizona and Utah use the federal one), or directly from a carrier. Marketplace plans are the only ones that carry the premium tax credit, which lowers the monthly cost for households under an income ceiling, so a household that qualifies is generally better off enrolling there even if it could buy the same plan direct.",
    "We are licensed to enroll you in marketplace and off-marketplace plans from the carriers we represent, plus short-term and supplemental products where they fit. The analysis takes your doctors, your prescriptions, your expected use and your household income estimate and shows what each plan would cost over a year of light use and a year of heavy use. When the plan you have is the right one, that is the finding.",
  ],
  coverageBlocks: [
    { heading: "Deductibles, coinsurance and the out-of-pocket maximum", paragraphs: ["The deductible is what you pay before the plan shares cost, though preventive care and, on many plans, primary-care visits and generic drugs are covered before it with a flat copay. After the deductible you pay coinsurance, a share of the allowed amount, until your spending for the year reaches the out-of-pocket maximum; from there the plan pays covered in-network care in full until the plan year resets. Family plans carry both an individual and a family figure for each. Suppose a plan has a $3,000 deductible and a $7,000 out-of-pocket maximum: a hospital stay billed at $40,000 would cost you the deductible plus coinsurance up to $7,000 and no more, which is the number to plan a budget around, not the premium."] },
    { heading: "Metal tiers", paragraphs: ["Marketplace plans are grouped into bronze, silver, gold and platinum by roughly what share of the total cost of care the plan pays across everyone enrolled. Bronze has the lowest premium and the highest deductible; platinum the reverse; silver and gold sit between. Silver is special on the marketplace: households below an income ceiling get cost-sharing reductions that shrink a silver plan's deductible and maximum without changing the premium, which can make silver pay better than gold for them. The tier is not a measure of network size or provider quality, only of the cost split."] },
    { heading: "Networks: HMO, PPO and EPO", paragraphs: ["An HMO covers care only from its network, needs a primary-care physician and referrals to specialists, and pays nothing outside the network except emergencies. A PPO pays for out-of-network care at a lower share and without referrals, for a higher premium. An EPO uses a network like an HMO but usually without referrals. Networks in the individual market are narrower than employer networks, and they differ plan by plan even within the same carrier, so the first step in any comparison is checking whether your doctors and your hospital are in the specific plan's network, not the carrier's."] },
    { heading: "Prescription drugs", paragraphs: ["Each plan has a formulary that lists covered drugs in tiers, from generics with a small copay up to specialty drugs paid by coinsurance after the deductible. A drug that is not on the formulary is paid in full by you unless an exception is approved. Prior authorisation, step therapy and quantity limits apply to some drugs, and mail-order pricing is often lower for maintenance medications. We run your prescriptions against each plan's formulary before recommending one."] },
    { heading: "Off-marketplace, short-term and supplemental plans", paragraphs: ["Plans sold directly by carriers off the marketplace follow the same rules but carry no tax credit. Short-term medical plans are not ACA plans: they can decline applicants, exclude pre-existing conditions and cap benefits, and their allowed duration is set by federal rule and by each state. They can bridge a gap between jobs for someone healthy, and they are a poor substitute for a full plan. Supplemental policies, such as accident, critical illness and hospital indemnity, pay a fixed cash amount on an event and are used to blunt a high deductible rather than to replace a health plan."] },
  ],
  covered: [
    "Hospital stays, surgery and emergency room visits, in network, after the deductible",
    "Preventive care such as screenings and immunisations, before the deductible",
    "Doctor visits and specialist care, with copays or coinsurance",
    "Prescription drugs on the plan's formulary",
    "Maternity, newborn care and pediatric dental and vision",
    "Mental health and substance use treatment on the same terms as medical care",
    "Lab work, imaging and rehabilitation services",
  ],
  notCovered: [
    "Care outside the network on an HMO or EPO, other than an emergency",
    "Adult dental and vision on most plans, which need a separate policy",
    "Cosmetic procedures and most experimental treatments",
    "Balance bills from an out-of-network provider above the allowed amount, on a PPO",
    "Drugs not on the formulary until an exception is granted",
    "Care received after the plan lapses for non-payment of premium",
    "Long-term custodial care",
  ],
  discounts: [
    { name: "Premium tax credit", description: "A marketplace subsidy for households under an income ceiling, paid straight to the carrier each month or claimed at tax time. It is reconciled on the tax return, so an income estimate that is too low is repaid later." },
    { name: "Cost-sharing reductions", description: "For eligible households that pick a silver plan: a lower deductible and out-of-pocket maximum at the same premium." },
    { name: "Tobacco-free rating", description: "Carriers may charge tobacco users more within limits set by federal rule; the non-user rate is the lower one." },
    { name: "Health savings account pairing", description: "A qualifying high-deductible plan lets you fund an HSA with pre-tax money, which lowers the effective cost of the deductible rather than the premium." },
    { name: "Paperless and autopay", description: "Some carriers shave the premium for electronic billing and automatic payment." },
  ],
  faqs: [
    { question: "When can I enroll in an individual plan?", answer: ["During the annual open enrollment period, or within a special enrollment period that opens after a qualifying event such as losing job-based coverage, marriage, a birth, or a move to a new county. Outside those windows the marketplace and carriers will not take a new application, which is why a gap in coverage is hard to fix mid-year. Enrollment in a plan runs to the end of the calendar year; you can change plans only at open enrollment or with another qualifying event."] },
    { question: "Bronze or gold: which costs less overall?", answer: ["It depends on how much care you use. Add twelve months of premium to the deductible and the likely coinsurance for each plan and compare the totals for a light year and a heavy year. Bronze wins the light year and loses the heavy one; gold does the reverse, and the crossover point is what the analysis finds. For example, say a bronze plan costs $300 a month with a $7,000 maximum and a gold plan costs $500 a month with a $3,000 maximum: the gold plan costs less in any year in which you would otherwise reach the bronze maximum, and more in a year you barely see a doctor."] },
    { question: "What if my doctor is out of network?", answer: ["On an HMO or EPO the visit is not covered outside an emergency. On a PPO the plan pays a lower share of its allowed amount and the doctor may balance-bill you for the rest, and the out-of-pocket maximum does not cap that balance. Federal surprise-billing rules limit balance bills for emergencies and for out-of-network providers working inside an in-network facility, but not for a planned visit you chose. Before enrolling, we confirm the doctor in the plan's own directory, since carrier-wide directories are unreliable."] },
    { question: "Can I be turned down for a pre-existing condition?", answer: ["Not on an ACA-compliant plan, on or off the marketplace: the carrier accepts you during an enrollment window and cannot price the plan by your health. Short-term and some indemnity products can and do decline or exclude conditions, which is the main reason they cost less. Age, location, household size and tobacco use are the only rating factors an ACA plan can use."] },
    { question: "What happens if I estimate my income wrong for the tax credit?", answer: ["The credit is advanced monthly on the estimate and reconciled on your federal return against actual income. Earn more than estimated and you repay some or all of the advance, subject to caps for lower incomes; earn less and you receive the difference as a refund. Reporting an income change to the marketplace during the year adjusts the advance and keeps the reconciliation small."] },
    { question: "Is a health savings account worth it?", answer: ["If a qualifying high-deductible plan fits your care needs, yes: contributions are pre-tax, growth is untaxed and withdrawals for medical costs are untaxed, and the balance rolls over year after year. The account also changes the deductible math, because you are paying it with untaxed money. It is not a reason to choose a high deductible you could not cover in a bad year."] },
  ],
  relatedProducts: ["dental-and-vision-insurance", "medicare", "life-insurance", "travel-insurance"],
  seo: { description: "How individual and family health plans work: deductibles, coinsurance and the out-of-pocket maximum, metal tiers, HMO versus PPO networks, formularies and the marketplace tax credit, from an independent agency in Arizona, Nevada, Utah and Idaho." },
};
