import type { ProductDraft } from "../types.mts";

export const draft: ProductDraft = {
  summary: "Permanent coverage with a flexible premium and a cash value that earns interest tied to a stock index, with a cap on the upside and a floor on the downside, without holding the stocks. The illustration is a projection, the charges rise with age, and how it is funded decides whether it works.",
  intro: [
    "Universal life took whole life apart into its pieces. Premiums go into an account; each month the carrier deducts the cost of insurance for the death benefit that month, plus administrative and per-thousand charges; the balance earns interest. The owner chooses how much to pay, within a minimum that keeps the policy alive and a maximum the tax code allows, and can change it. Indexed universal life is the version where the interest credited is tied to the movement of a market index rather than a rate the carrier declares.",
    "The index link works through options, not stocks. The cash value sits in the carrier's general account, and the carrier uses part of the interest it would have credited to buy options on the index. If the index rises over the crediting period, the account is credited with the gain up to a cap, sometimes scaled by a participation rate; if the index falls, the floor applies and the account is credited nothing, or a small fixed amount, rather than losing value. Dividends from the index's stocks are not included. The cap, the participation rate and the floor are set by the carrier and can be changed on existing policies within the contract's limits.",
    "The trap is in the charges. The cost of insurance rises every year with age, and in the later decades it becomes large; a policy funded at the minimum in the early years, or one whose credited interest fell short of the illustration, can find the charges consuming the cash value and lapse when the owner is old, with nothing paid. A policy funded near the maximum from the start behaves very differently, which is why the funding plan matters more than the product.",
    "The analysis reads the illustration at the guaranteed minimum interest and maximum charges, at a moderate rate, and at the agent's rate, and tells you whether the design works in the poor case and not only the good one. For a person who has not yet filled a retirement account, or who would fund the policy lightly, the usual recommendation is term and the retirement account.",
  ],
  coverageBlocks: [
    { heading: "Death benefit options", paragraphs: ["The owner chooses a level death benefit, where the face amount stays fixed and the cash value grows inside it, or an increasing benefit, where the beneficiaries receive the face amount plus the cash value. The increasing option costs more each month because the amount at risk to the carrier does not shrink as cash value grows; the level option is cheaper and is usually switched to once accumulation is the goal. The policy has to keep a minimum gap between cash value and death benefit under the tax code to remain life insurance, and the carrier raises the benefit automatically if the cash value gets too close."] },
    { heading: "Interest crediting: caps, floors and participation", paragraphs: ["A crediting method defines the period, usually a year, and how the index change is measured, point to point or averaged. The cap is the most the account can be credited in the period regardless of the index; the participation rate is the share of the index gain that counts; the floor is the least it can be credited, commonly zero. Some designs offer an uncapped strategy with a lower participation rate or a spread deducted from the gain, and some charge a fee for a higher cap. The strategies can be mixed and changed each year, and the carrier can reset caps and participation rates on existing policies, which the guaranteed minimum column of the illustration assumes it does."] },
    { heading: "Charges and the cost of insurance", paragraphs: ["Every month the carrier deducts a premium load on money coming in, a per-thousand charge on the face amount for the first years, a flat administrative fee, and the cost of insurance, which is the mortality charge on the difference between the death benefit and the cash value at your current age. That last item climbs steeply past the mid-sixties. Illustrations show the current charges and the maximum charges the contract allows; the carrier can move toward the maximum, and the cash value has to be able to survive that."] },
    { heading: "Loans and withdrawals", paragraphs: ["The cash value can be withdrawn up to the premiums paid without tax, and borrowed beyond that. A standard loan charges interest and moves the borrowed amount to a fixed account; a participating or indexed loan leaves the money in the index strategy while charging interest, which can win or lose depending on the year. Loans reduce the death benefit and, if they compound faster than the account, can collapse the policy and trigger tax on the gain. This mechanism is the basis of the retirement income designs the product is sold for, and it works only if the policy has been funded heavily for many years."] },
    { heading: "Surrender charges and the no-lapse guarantee", paragraphs: ["A surrender charge applies if the policy is cancelled or the face amount reduced in the early years, often for more than a decade, and it can take the whole cash value in the first few years. Some contracts offer a no-lapse guarantee that keeps the policy in force to a stated age as long as a set premium is paid on time, regardless of the account; it is worth having, and it is usually lost the moment a premium is missed or a loan is taken."] },
  ],
  covered: [
    "The death benefit to beneficiaries as long as the policy stays in force",
    "Interest credited from index gains up to the cap and never below the floor",
    "Cash value growth that is not taxed while it stays in the policy",
    "Premiums that can be raised, lowered or paused within the contract's limits",
    "Withdrawals up to the premiums paid, and loans beyond, without a credit check",
    "The policy kept in force by a no-lapse guarantee where the required premium is paid",
    "An accelerated benefit for terminal, and on some contracts chronic, illness",
  ],
  notCovered: [
    "Stock dividends, which the index credit leaves out",
    "Index gains above the cap or beyond the participation rate",
    "The full illustrated values: the illustration is a projection under assumptions, not a promise",
    "A death after the policy lapses because charges exhausted the cash value",
    "Cash value in the early years, which surrender charges can consume entirely",
    "Suicide and material misstatement within the contract's exclusion and contestability periods",
    "Any part of the death benefit offset by an unpaid loan",
  ],
  discounts: [
    { name: "Preferred rate class", description: "The cost of insurance is charged at the rate class assigned at issue and deducted every month for life, so a better class matters more here than on term." },
    { name: "Level death benefit option", description: "The level option shrinks the amount at risk as cash value grows, reducing the monthly mortality charge." },
    { name: "Minimum face amount for the premium", description: "Designs built for accumulation set the death benefit as low as the tax code allows for the intended premium, which cuts the per-thousand and mortality charges." },
    { name: "Front-loaded funding", description: "Funding the policy near the maximum in the early years builds a cash value that carries the later charges and earns more credit." },
    { name: "Low-cost strategy choices", description: "Choosing a capped strategy without a strategy fee, and a standard loan over a participating loan, removes charges that show up only in the poor scenario." },
  ],
  faqs: [
    { question: "Can I lose money in an IUL?", answer: ["Not to the index, because of the floor, but yes to the charges. In a year the index falls the account is credited nothing while the cost of insurance, fees and any loan interest are still deducted, so the cash value goes down. Over a run of flat years on a lightly funded policy, that is how the policy lapses. The floor protects against market loss; nothing protects against underfunding."] },
    { question: "Why does the illustration show such large numbers?", answer: ["Because it assumes a constant credited rate every year for decades, and compounding at any steady rate produces large numbers. Real index crediting is lumpy, caps get lowered, and a run of poor years early in a policy changes the outcome. Regulators limit the rate that can be illustrated, and even so the projected column is the sales case. Ask for the illustration at a rate several points lower and at the guaranteed minimum, and judge the design by those."] },
    { question: "How does the cap work?", answer: ["Suppose the cap is ten percent and the participation rate is one hundred percent: if the index rises fifteen percent in the year, the account is credited ten; if it rises six, the account gets six; if it falls, the account gets the floor, usually zero. The carrier sets the cap each year from the price of the options it buys, so when interest rates are low and volatility is high, caps fall. The cap in the sales illustration is today's cap, not a promise."] },
    { question: "Is this a good way to save for retirement?", answer: ["It can be, for someone who has already filled a retirement account and a health savings account, will fund the policy heavily for many years, wants a death benefit anyway, and can leave the money alone through the surrender period. For everyone else the charges make it an expensive way to hold an index position, and the retirement account without the insurance costs is the better vehicle."] },
    { question: "What happens if I stop paying premiums?", answer: ["Universal life lets you, and the account keeps paying the monthly charges until it runs out. On a well-funded policy that can run for decades; on a lightly funded one the carrier's lapse notices arrive within a few years, and a no-lapse guarantee that required a premium is usually forfeited. The annual statement shows the account, the charges and how long the policy would last at current rates with no further premium, and it is worth reading each year."] },
    { question: "How is IUL different from variable universal life?", answer: ["Variable universal life invests the cash value in sub-accounts that hold stocks and bonds directly, with no cap and no floor, and it is a security sold by prospectus. Indexed universal life holds no securities; it credits interest by formula from an index and is regulated as insurance. The variable form carries the full market gain and the full market loss; the indexed form trades most of the upside for a floor on the downside."] },
  ],
  relatedProducts: ["life-insurance", "term-life-insurance", "whole-life-insurance", "annuities"],
  seo: { description: "Indexed universal life (IUL) explained honestly: how index crediting with caps, floors and participation rates works, the cost of insurance and other charges, loans, surrender charges, and why the illustration is not a promise. Independent agency in Arizona, Nevada, Utah and Idaho." },
};
