import type { ProductDraft } from "../types.mts";

export const draft: ProductDraft = {
  summary: "Federal health insurance for people who qualify by age or by disability, in parts that each pay for a different kind of care. We explain how Original Medicare, Medicare Advantage, Part D and Medigap fit together and help you enroll in the plans we represent that suit your situation.",
  intro: [
    "Medicare is the federal health insurance program for people who qualify by age and for younger people who qualify through a disability or certain conditions. It is not one policy but a set of parts, and each part pays for a different category of care with its own premiums, deductibles and cost-sharing. Most of the decisions people make about Medicare are decisions about how to fill the gaps between the parts.",
    "Original Medicare is Parts A and B, run by the federal government, and it pays a share of the approved amount for covered services with no annual cap on what you pay out of pocket. Private plans fill in around it in two different ways: a Medicare Advantage plan (Part C) replaces the way you receive Parts A and B, and a Medigap policy sits alongside Original Medicare to pay its cost-sharing. You choose one route or the other, not both, and Part D drug coverage attaches to whichever route you take.",
    "We are licensed to help you compare and enroll in Medicare Advantage, Part D and Medigap plans from the carriers we represent. We do not offer every plan available in your area, and any information we provide is limited to those plans. Medicare.gov and 1-800-MEDICARE list all options. The analysis takes your doctors, your prescriptions, your travel habits and your budget and shows what each route would cost you in a normal year and a bad one; if Original Medicare alone is the right answer, that is what we tell you.",
  ],
  coverageBlocks: [
    { heading: "Part A: hospital insurance", paragraphs: ["Part A covers inpatient hospital stays, skilled nursing facility care after a qualifying hospital stay, hospice and some home health care. People who paid Medicare taxes for enough working quarters pay no monthly premium for Part A; others can buy it. It carries a deductible per benefit period rather than per year, and a long stay moves into daily coinsurance once the covered days in a benefit period are used, so separate hospitalisations can trigger the deductible more than once in a year."] },
    { heading: "Part B: medical insurance", paragraphs: ["Part B covers doctor visits, outpatient care, durable medical equipment, preventive services, lab work and drugs given in a clinic. It has a monthly premium, deducted from Social Security for most enrollees, that rises with income above thresholds the government resets each year, and an annual deductible after which Medicare pays its share of the approved amount and you pay the rest. Providers who accept assignment agree to the approved amount; those who do not can bill a limited excess charge, which is one of the things Medigap letters differ on."] },
    { heading: "Part C: Medicare Advantage plans from private insurers", paragraphs: ["A Medicare Advantage plan is offered by a private insurer under contract with Medicare and covers everything Parts A and B cover, usually with Part D bundled in and often with extras such as dental, vision or a fitness benefit. In exchange it uses a network, typically an HMO or PPO, and its own copays, and it sets an annual out-of-pocket maximum that Original Medicare lacks. Plans, networks and benefits change every year and vary by county. A plan that suits you is one whose network includes your doctors and whose formulary includes your prescriptions; we check both before recommending one."] },
    { heading: "Part D: prescription drug coverage", paragraphs: ["Part D is drug coverage from private plans, either standalone next to Original Medicare or built into an Advantage plan. Each plan has a formulary, tiers that set the copay for each drug, a deductible in some plans, and pharmacy networks with preferred and standard pricing. Federal rules cap what an enrollee pays out of pocket for covered drugs in a year, and the cap and the phases beneath it are reset annually. Going without creditable drug coverage after first becoming eligible adds a late enrollment penalty to the premium for as long as you have Part D, which is why we ask about drug coverage even from people who take nothing today."] },
    { heading: "Medigap, the Medicare supplement", paragraphs: ["A Medigap policy is sold by a private insurer to pay the deductibles, coinsurance and copays that Original Medicare leaves behind. Plans are standardised by letter, so a given letter pays the same benefits from any insurer, and the differences are price, rate-increase history and household discounts. Medigap has no network: any provider that accepts Medicare accepts it, in any state, which is why frequent travellers and people with doctors in more than one city often prefer this route. The trade is a monthly premium on top of Part B, paid every year, against low and predictable costs when care is needed."] },
    { heading: "Enrollment periods", paragraphs: ["Medicare has several enrollment windows, and which one you are in decides what you can do. The initial enrollment period surrounds the month you first become eligible. The general enrollment period, each year, is for people who missed the initial one, and it can carry a Part B late penalty that lasts as long as you have Part B. The annual election period, each autumn, is when anyone can change Advantage or Part D plans for the following year, and a separate Advantage open enrollment period early in the year allows one change for people already in an Advantage plan. Special enrollment periods open after events such as losing employer coverage or moving out of a plan's service area.", "Medigap has its own rule: a one-time open enrollment window tied to Part B enrollment in which an insurer accepts you regardless of health, after which medical underwriting applies in most states."] },
  ],
  covered: [
    "Inpatient hospital stays, skilled nursing after a qualifying stay, and hospice under Part A",
    "Doctor visits, outpatient care, preventive services and equipment under Part B",
    "Prescription drugs on a plan's formulary under Part D",
    "Original Medicare's deductibles and coinsurance, paid by a Medigap policy",
    "An annual out-of-pocket maximum inside a Medicare Advantage plan",
    "Emergency care anywhere in the country under Original Medicare, and by plan rules under Advantage",
  ],
  notCovered: [
    "Long-term custodial care in a nursing home",
    "Routine dental, vision and hearing under Original Medicare, unless an Advantage plan adds them",
    "Care outside the United States, apart from limited foreign travel emergency benefits in some Medigap letters",
    "Cosmetic surgery and most alternative treatments",
    "Drugs not on a Part D plan's formulary, until an exception is approved",
    "Out-of-network care in an HMO Advantage plan outside an emergency",
  ],
  faqs: [
    { question: "Do I have to sign up if I am still working?", answer: ["If you or your spouse are actively employed and covered by that employer's group plan, you can usually delay Part B and Part D without a penalty and enroll later under a special enrollment period when the job or the coverage ends. Whether the employer plan is primary or secondary to Medicare depends on the employer's size, and a small employer's plan can become secondary, which makes delaying Part B costly. Many people take Part A when first eligible because it carries no premium for them, but doing so ends eligibility to contribute to a health savings account, so the timing is worth working out in advance."] },
    { question: "Medicare Advantage or Medigap: how do I choose?", answer: ["Start from your doctors and your travel. Advantage plans are network products with lower up-front premiums and costs that rise when you use care, capped at the plan's annual maximum. Medigap plus Part D costs more every month and very little at the point of care, with no network. Someone healthy today who values a low premium and stays near home often chooses Advantage; someone with ongoing conditions, out-of-state family or a preferred specialist often chooses Medigap. Switching from Advantage back to Medigap later can require medical underwriting, so the first choice carries more weight than it appears to."] },
    { question: "What is the Part D late enrollment penalty?", answer: ["A permanent addition to your Part D premium, calculated from the number of full months you went without Part D or other creditable drug coverage after first becoming eligible. It is paid for as long as you have Part D. Employer, union, VA and some retiree plans count as creditable if they say so in writing, and keeping that letter is what avoids the penalty later."] },
    { question: "Does Medicare cover me when I travel?", answer: ["Original Medicare pays anywhere in the United States and its territories but almost nothing outside them. Some Medigap letters include a foreign travel emergency benefit with its own deductible and lifetime limit. Advantage plans cover emergencies nationwide but route routine care through their network, and a long stay outside the service area can end enrollment. For extended travel abroad, a separate travel medical policy is the usual answer."] },
    { question: "What does it cost to work with an agent?", answer: ["Nothing beyond what you would pay enrolling directly: the premium for a plan is the same whether you enroll through us, through the carrier or through Medicare.gov, and the carrier pays us a commission set within federal limits for Advantage and Part D. We are paid only on plans we place, and we do not offer every plan in your area, which is why we also point you to Medicare.gov and 1-800-MEDICARE for the full list."] },
    { question: "Can I change plans if I made the wrong choice?", answer: ["Within the enrollment windows, yes. The annual election period allows changes to Advantage and Part D for the following year, and the Advantage open enrollment period allows one change for people already in an Advantage plan. Medigap can be applied for at any time, but outside your one-time open enrollment window or a guaranteed issue right, the insurer can underwrite and decline. A special enrollment period also opens after certain events, such as a move or a plan leaving your county."] },
  ],
  relatedProducts: ["health-insurance", "dental-and-vision-insurance", "life-insurance", "annuities"],
  seo: { description: "Medicare Parts A, B, C and D and Medigap explained neutrally: what each pays, how enrollment periods work and how to choose between Medicare Advantage and a supplement, from a licensed independent agency in Arizona, Nevada, Utah and Idaho." },
};
