/**
 * pnpm fonts:fallbacks — writes app/(frontend)/fonts.fallback.css: metric-
 * compatible fallback faces ("Archivo Fallback" over Arial, "Source Serif
 * Fallback" over Georgia) with size-adjust, ascent-, descent- and line-gap-
 * override computed from the fonts' own metrics (@capsizecss/metrics), so
 * the swap causes no layout shift. The brand's token font stacks already
 * name these fallback families.
 */
import { writeFileSync } from "node:fs";
import { createFontStack } from "@capsizecss/core";
import archivo from "@capsizecss/metrics/archivo";
import arial from "@capsizecss/metrics/arial";
import georgia from "@capsizecss/metrics/georgia";
import sourceSerif4 from "@capsizecss/metrics/sourceSerif4";

const sans = createFontStack([archivo, arial], { fontFaceProperties: { fontDisplay: "swap" } });
const serif = createFontStack([sourceSerif4, georgia], { fontFaceProperties: { fontDisplay: "swap" } });
const rename = (css: string, from: string, to: string) => css.replaceAll(`"${from}"`, `"${to}"`).replaceAll(`'${from}'`, `"${to}"`);
const out = [
  "/* GENERATED by scripts/font-fallbacks.mts from @capsizecss/metrics. Do not edit. */",
  rename(sans.fontFaces, "Archivo Fallback", "Archivo Fallback").replace(/font-family: "Archivo Fallback: Arial"/g, 'font-family: "Archivo Fallback"'),
  rename(serif.fontFaces, "Source Serif 4 Fallback", "Source Serif Fallback").replace(/font-family: "Source Serif 4 Fallback: Georgia"/g, 'font-family: "Source Serif Fallback"'),
  "",
].join("\n");
writeFileSync(new URL("../app/(frontend)/fonts.fallback.css", import.meta.url), out);
console.log(out);
