/**
 * pnpm fonts:fallbacks — writes app/(frontend)/fonts.fallback.css: metric-
 * compatible fallback faces (Figtree over Arial, Instrument Serif over
 * Georgia, DM Mono over Courier New) with size-adjust, ascent-, descent- and line-gap-
 * override computed from the fonts' own metrics (@capsizecss/metrics), so
 * the swap causes no layout shift. The brand's token font stacks already
 * name these fallback families.
 */
import { writeFileSync } from "node:fs";
import { createFontStack } from "@capsizecss/core";
import arial from "@capsizecss/metrics/arial";
import courierNew from "@capsizecss/metrics/courierNew";
import dmMono from "@capsizecss/metrics/dMMono";
import figtree from "@capsizecss/metrics/figtree";
import georgia from "@capsizecss/metrics/georgia";
import instrumentSerif from "@capsizecss/metrics/instrumentSerif";

// Editorial system: Figtree over Arial, Instrument Serif over Georgia, DM Mono over Courier New.
const text = createFontStack([figtree, arial], { fontFaceProperties: { fontDisplay: "swap" } });
const display = createFontStack([instrumentSerif, georgia], { fontFaceProperties: { fontDisplay: "swap" } });
const mono = createFontStack([dmMono, courierNew], { fontFaceProperties: { fontDisplay: "swap" } });
const rename = (css: string, from: string, to: string) => css.replaceAll(`"${from}"`, `"${to}"`).replaceAll(`'${from}'`, `"${to}"`);
const out = [
  "/* GENERATED by scripts/font-fallbacks.mts from @capsizecss/metrics. Do not edit. */",
  text.fontFaces.replace(/font-family: "Figtree Fallback: Arial"/g, 'font-family: "Figtree Fallback"'),
  display.fontFaces.replace(/font-family: "Instrument Serif Fallback: Georgia"/g, 'font-family: "Instrument Serif Fallback"'),
  mono.fontFaces.replace(/font-family: "DM Mono Fallback: Courier New"/g, 'font-family: "DM Mono Fallback"'),
  "",
].join("\n");
writeFileSync(new URL("../app/(frontend)/fonts.fallback.css", import.meta.url), out);
console.log(out);
