import type { ArticleDraft } from "../types.mts";

export const draft: ArticleDraft = {
  title: "Homeowners insurance disclosure requirements in Arizona",
  excerpt: "What an Arizona homeowner or buyer is entitled to see: the claims history report, the reasons behind a declined or rated application, flood and wildfire information, roof and valuation terms, and the written notice that has to come before a cancellation or non-renewal.",
  sections: [
    {
      heading: "",
      paragraphs: [
        "A home policy is priced from information the homeowner rarely sees: a database of past claims, an insurance score built from credit history, a wildfire model, a flood map and a replacement cost estimate generated by software. Arizona and federal law give consumers a right to see much of it, and to be told in writing when it counts against them. Knowing where each disclosure comes from turns an unexplained premium into a list of things that can be checked and, sometimes, corrected.",
        "This article covers the disclosures that matter at purchase and at renewal for a house in Arizona. It points to the regulator, the Arizona Department of Insurance and Financial Institutions, for anything that turns on a specific deadline, and marks those deadlines for verification rather than quoting them.",
      ],
    },
    {
      heading: "The claims history report",
      paragraphs: [
        "Carriers share property claims through a national database, and the report drawn from it is usually called a CLUE report, after the Comprehensive Loss Underwriting Exchange. It lists claims made on a property and by a person over a look-back period: the date, the type of loss and the amount paid. Because it is a consumer report under the federal Fair Credit Reporting Act, you can request your own copy free once a year and dispute an entry that is wrong.",
        "The report follows the address as well as the owner. A buyer inherits the house's history, so a roof claim or a water loss filed by the previous owner can affect the buyer's quote. Sellers can order the property report and share it, and a buyer can reasonably ask for it before the inspection period ends.",
        "One distinction trips people up. A phone call to ask whether something is covered is not a claim, but some carriers log it as a loss notice if it is phrased as a report of damage. Whether an Arizona carrier may use a question that never became a claim against you is governed by state insurance rules, and the Department of Insurance and Financial Institutions can say how they apply. Ask your agent the coverage question first; call the carrier when you intend to file.",
      ],
    },
    {
      heading: "Insurance scores and adverse action notices",
      paragraphs: [
        "Arizona permits carriers to use credit-based insurance scores in underwriting and rating, within limits the state sets on how the score may be used and when it must be refreshed; the Department of Insurance and Financial Institutions can explain those limits. When a score, or any item on a consumer report, leads to a higher premium or a declined application, the carrier has to send an adverse action notice. That notice names the reporting agency, explains how to get a free copy and tells you how to dispute it.",
        "Read the notice rather than filing it away. A medical collection that was paid, an account that belongs to someone else, or a closed card reported as open can all move a score, and correcting the credit file can change the premium at the next rating.",
      ],
    },
    {
      heading: "Flood zone and drainage information",
      paragraphs: [
        "A home policy excludes flood, and no Arizona rule requires a carrier to tell you whether a house floods. The disclosures come from elsewhere. FEMA flood maps show whether a property sits in a special flood hazard area, and a lender making a federally backed loan on a house in one must require flood insurance and tell the borrower so before closing. The seller's property disclosure statement commonly used in Arizona sales asks about past flooding, drainage problems and soil conditions.",
        "Neither of those covers the ordinary Arizona flood: a flash flood down a wash, or a street that ponds in a monsoon storm, on a lot outside the mapped zone. The absence of a lender requirement is not a finding that the house is dry. If the seller's disclosure mentions water, or the lot sits low against a wash, ask for a flood quote before closing, because a flood policy has a waiting period before it takes effect.",
      ],
    },
    {
      heading: "Wildfire scores and inspection findings",
      paragraphs: [
        "Carriers writing in the rim country, the Prescott area and the foothills around Tucson score each address for wildfire exposure. The score can raise the premium, trigger an inspection or lead to a decision not to renew. A homeowner who receives any of those outcomes can ask the carrier for the reason, and the notice of a non-renewal has to state one; the rules on content and timing are set by Arizona law, and the Department of Insurance and Financial Institutions can confirm them.",
        "Inspection findings are worth requesting in writing. A report that says brush within the first zone around the house, an unscreened vent or a wood roof drove the decision is a list of work. Completed and photographed, that work is the basis for asking the carrier to reconsider or for presenting the house to a different carrier.",
      ],
    },
    {
      heading: "Roof and valuation terms",
      paragraphs: [
        "Two terms on the declarations page decide the size of the largest likely claim, and both have to be shown there. The first is how the roof is paid: at replacement cost, or on a schedule that pays actual cash value once a roof passes a certain age. A roof payment schedule or an actual cash value roof endorsement will appear as a listed form, and it is easy to miss at renewal when the carrier adds it.",
        "The second is the dwelling limit. The carrier's software produces a replacement cost estimate, but the limit is the homeowner's choice. Suppose the estimate says $450,000 and a local builder says a comparable rebuild would cost $520,000. A limit of $450,000 leaves a gap of $70,000 on a total loss unless the policy carries an extended replacement cost endorsement. These are hypothetical figures, and the point is that the estimate is a starting number to question, not a disclosure of what a rebuild will cost.",
      ],
    },
    {
      heading: "Cancellation and non-renewal notices",
      paragraphs: [
        "Arizona treats cancellation and non-renewal as different events. During a short initial period after a new policy starts, a carrier has wide latitude to cancel after underwriting the house. Once that period passes, cancellation mid-term is limited to specific reasons such as non-payment, fraud or a material change in the risk. The length of the initial period and the list of permitted reasons are set by Arizona law; the cancellation notice names the reason, and the Department of Insurance and Financial Institutions can confirm whether it is a permitted one.",
        "Non-renewal happens at the end of a term and requires advance written notice mailed to the named insured; Arizona sets how far in advance, and the notice itself states the date coverage ends. The lender usually receives a copy. The notice window is the time to find replacement coverage; a lapse on a mortgaged house leads the lender to buy force-placed insurance, which protects the lender's interest at a higher price and with narrower coverage.",
      ],
    },
    {
      heading: "What to ask for",
      paragraphs: ["A short list for a buyer before closing, or an owner before renewal."],
      bullets: [
        "Your own CLUE report and, for a purchase, the property's report from the seller.",
        "Any adverse action notice, and the credit report it names.",
        "The flood zone determination from the lender and the seller's disclosure answers on flooding and drainage.",
        "The inspection report or wildfire score reason, if the carrier cited either.",
        "The declarations page, with every listed form, so the roof terms and dwelling limit can be read line by line.",
        "Any cancellation or non-renewal notice, with the date it was mailed.",
      ],
    },
    {
      heading: "Where to take a question",
      paragraphs: [
        "If a carrier will not explain a decision, or a notice arrives without the information it should contain, the Arizona Department of Insurance and Financial Institutions takes consumer complaints and publishes guidance at https://difi.az.gov/. Before that step, send us the notice and the declarations page. We read them against the carriers we represent, explain what drove the decision and, if the current policy is still the right one once the facts are corrected, we say so. The analysis costs nothing.",
      ],
    },
  ],
  relatedProducts: ["home-insurance", "flood-insurance", "landlord-rental-property-insurance"],
  relatedArticles: ["how-to-get-coverage-after-a-non-renewal", "insurance-checklist-for-first-time-homebuyers", "how-to-prepare-your-home-for-a-wildfire-insurance-inspection", "actual-cash-value-vs-replacement-cost-coverage", "how-to-improve-your-insurance-score"],
  relatedTerms: ["declarations-page", "replacement-cost", "flood-zone", "force-placed-insurance", "underwriting", "wildfire-mitigation"],
  relatedStates: ["arizona"],
};
