/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    states: State;
    cities: City;
    'location-overrides': LocationOverride;
    articles: Article;
    'glossary-terms': GlossaryTerm;
    pages: Page;
    agents: Agent;
    carriers: Carrier;
    users: User;
    media: Media;
    redirects: Redirect;
    forms: Form;
    leads: Lead;
    'quote-sessions': QuoteSession;
    'rum-samples': RumSample;
    tenants: Tenant;
    'referral-programs': ReferralProgram;
    'referral-reward-rules': ReferralRewardRule;
    referrers: Referrer;
    referrals: Referral;
    'reward-ledger': RewardLedger;
    'referral-events': ReferralEvent;
    'message-templates': MessageTemplate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    states: StatesSelect<false> | StatesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'location-overrides': LocationOverridesSelect<false> | LocationOverridesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'glossary-terms': GlossaryTermsSelect<false> | GlossaryTermsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    carriers: CarriersSelect<false> | CarriersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'quote-sessions': QuoteSessionsSelect<false> | QuoteSessionsSelect<true>;
    'rum-samples': RumSamplesSelect<false> | RumSamplesSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'referral-programs': ReferralProgramsSelect<false> | ReferralProgramsSelect<true>;
    'referral-reward-rules': ReferralRewardRulesSelect<false> | ReferralRewardRulesSelect<true>;
    referrers: ReferrersSelect<false> | ReferrersSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    'reward-ledger': RewardLedgerSelect<false> | RewardLedgerSelect<true>;
    'referral-events': ReferralEventsSelect<false> | ReferralEventsSelect<true>;
    'message-templates': MessageTemplatesSelect<false> | MessageTemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'compliance-settings': ComplianceSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'compliance-settings': ComplianceSettingsSelect<false> | ComplianceSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Derived from name when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  /**
   * Tier 1 gets product × city pages. Promote a Tier 2 line only with search evidence.
   */
  tier: '1' | '2';
  category: 'Personal' | 'Commercial';
  /**
   * Medicare and annuities have no discounts to describe (docs/RECONCILIATION.md).
   */
  thirdSubpage: 'discounts-faq' | 'plans-enrollment-faq';
  /**
   * Sub-line of a hub product, e.g. term life under life insurance.
   */
  parent?: (number | null) | Product;
  /**
   * Every page for this product carries the TPMO/CMS disclaimer and routes referrals to the Medicare rule set.
   */
  medicareTouching?: boolean | null;
  /**
   * One paragraph, used on hubs and cards.
   */
  summary?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What the policy does, one block per coverage part.
   */
  coverageBlocks?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  covered?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  notCovered?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  discounts?:
    | {
        name: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Leave blank to derive from the document. Title ≤ 60, description ≤ 155.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Only an admin can set reviewed. Everything else renders noindex.
   */
  reviewStatus: 'draft' | 'in-review' | 'reviewed';
  /**
   * Stamped when reviewStatus first becomes reviewed. Shown as "Last reviewed" and cited in Article JSON-LD.
   */
  reviewedAt?: string | null;
  /**
   * Promoted by changing this, not by rebuilding.
   */
  indexWave: '1' | '2' | '3';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    content?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "states".
 */
export interface State {
  id: number;
  name: string;
  /**
   * Derived from name when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  abbr: string;
  /**
   * Compliance-locked: admin only. Leave as a TODO token until the client supplies it. Never guess.
   */
  licenseNumber?: string | null;
  doi?: {
    name?: string | null;
    url?: string | null;
  };
  /**
   * One row per product per requirement. The source URL is mandatory: a minimum without a citation does not exist.
   */
  statutoryMinimums?:
    | {
        product: number | Product;
        /**
         * e.g. Bodily injury liability per person
         */
        coverage: string;
        /**
         * e.g. $25,000 — or a TODO token
         */
        requirement: string;
        sourceUrl: string;
        verifiedAt?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * State-level hazards and regulatory context that city pages inherit.
   */
  riskNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. UT no-fault PIP, NV SR-22 rules. Cite in statutoryMinimums; summarise here.
   */
  notableRegulatory?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thin cities are visible in the list: factsComplete counts the 7 CityFacts fields that are filled without a TODO token.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Derived from name when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  state: number | State;
  /**
   * Drives block order and selection on local pages so 380 pages do not share one sequence.
   */
  sizeBand: 'large' | 'mid' | 'small';
  /**
   * Every field feeds the 250 words of city-specific text. Unknown → {{TODO:city.<slug>.<field>}} token, never a guess.
   */
  cityFacts?: {
    county?: string | null;
    /**
     * TODO token until the client confirms offices/agents.
     */
    nearestOfficeOrAgent?: string | null;
    localHazards?:
      | (
          | 'monsoon-dust'
          | 'extreme-heat'
          | 'wildfire-wui'
          | 'hail'
          | 'freeze'
          | 'flood-plain'
          | 'flash-flood'
          | 'earthquake'
          | 'wind'
          | 'snow-load'
          | 'mountain-driving'
          | 'wildlife-collision'
          | 'urban-theft'
        )[]
      | null;
    /**
     * e.g. stucco tract, mid-century ranch, mountain cabin, HOA-heavy
     */
    housingStock?: string | null;
    /**
     * e.g. I-17 commute, mountain passes, tourist traffic
     */
    drivingContext?: string | null;
    /**
     * 3–5 real neighborhoods. Real. A fabricated one is worse than an empty list.
     */
    neighborhoods?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    notableRegulatory?: string | null;
  };
  /**
   * Optional city-level intro shared by every product page for this city.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  factsComplete?: number | null;
  factsMissing?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location-overrides".
 */
export interface LocationOverride {
  id: number;
  label?: string | null;
  product: number | Product;
  city: number | City;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Renders only when consent is on file. Legacy testimonials are never reused without written consent.
   */
  testimonial?: {
    quote?: string | null;
    /**
     * First name and city at most.
     */
    attribution?: string | null;
    consentOnFile?: boolean | null;
    consentDocument?: (number | null) | Media;
  };
  assignedAgent?: (number | null) | Agent;
  customFaqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: number;
  name: string;
  /**
   * Derived from name when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  /**
   * Inactive agents render nowhere.
   */
  active?: boolean | null;
  user?: (number | null) | User;
  title?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: {
    image?: (number | null) | Media;
    /**
     * No release, no photo on the site.
     */
    releaseOnFile?: boolean | null;
  };
  /**
   * Admin only. From the client's roster; never typed from memory.
   */
  licenses?:
    | {
        state: number | State;
        licenseNumber: string;
        /**
         * National Producer Number
         */
        npn?: string | null;
        id?: string | null;
      }[]
    | null;
  citiesServed?: (number | City)[] | null;
  products?: (number | Product)[] | null;
  email?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor' | 'agent' | 'partner')[];
  name?: string | null;
  /**
   * Empty = platform operator (every tenant).
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  /**
   * Tenant-level kill switch. False until counsel has filled every reward rule row for this tenant. The engine refuses to earn a reward while this is off.
   */
  referralsEnabled: boolean;
  /**
   * Used in referee messages ({{agencyName}}).
   */
  agencyDisplayName?: string | null;
  /**
   * Where referral operations notices go.
   */
  notifyEmail?: string | null;
  /**
   * Abuse limits. Rejections above these carry velocity-referrer / velocity-ip reason codes.
   */
  velocity: {
    perReferrerPerDay: number;
    perIpPerHour: number;
  };
  /**
   * A referee already referred within this window, by anyone, is a duplicate.
   */
  dedupeWindowDays: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Derived from title when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  section: 'guides' | 'state-requirements' | 'compare' | 'how-to' | 'life-events' | 'seasonal';
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A reviewed article links to at least 2 products.
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * A reviewed article links to at least 3 other articles.
   */
  relatedArticles?: (number | Article)[] | null;
  relatedStates?: (number | State)[] | null;
  relatedTerms?: (number | GlossaryTerm)[] | null;
  wordCount?: number | null;
  /**
   * Leave blank to derive from the document. Title ≤ 60, description ≤ 155.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Only an admin can set reviewed. Everything else renders noindex.
   */
  reviewStatus: 'draft' | 'in-review' | 'reviewed';
  /**
   * Stamped when reviewStatus first becomes reviewed. Shown as "Last reviewed" and cited in Article JSON-LD.
   */
  reviewedAt?: string | null;
  /**
   * Promoted by changing this, not by rebuilding.
   */
  indexWave: '1' | '2' | '3';
  generation: {
    status: 'pending' | 'drafted' | 'failed';
    generatedAt?: string | null;
    batch?: string | null;
    error?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms".
 */
export interface GlossaryTerm {
  id: number;
  term: string;
  /**
   * Derived from term when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  /**
   * Plain language. Never defines the term using itself.
   */
  definition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How it affects a policy in practice.
   */
  inPractice?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A short worked example.
   */
  example?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedTerms?: (number | GlossaryTerm)[] | null;
  relatedProducts?: (number | Product)[] | null;
  wordCount?: number | null;
  /**
   * Leave blank to derive from the document. Title ≤ 60, description ≤ 155.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Only an admin can set reviewed. Everything else renders noindex.
   */
  reviewStatus: 'draft' | 'in-review' | 'reviewed';
  /**
   * Stamped when reviewStatus first becomes reviewed. Shown as "Last reviewed" and cited in Article JSON-LD.
   */
  reviewedAt?: string | null;
  /**
   * Promoted by changing this, not by rebuilding.
   */
  indexWave: '1' | '2' | '3';
  generation: {
    status: 'pending' | 'drafted' | 'failed';
    generatedAt?: string | null;
    batch?: string | null;
    error?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Set from the template. Utility routes are noindex and excluded from the sitemap regardless of wave.
   */
  noindex?: boolean | null;
  /**
   * Leading and trailing slash, e.g. /claims/how-to-file/. Home is /.
   */
  path: string;
  template:
    | 'home'
    | 'static'
    | 'quote-hub'
    | 'claims-hub'
    | 'products-hub'
    | 'locations-hub'
    | 'carriers-hub'
    | 'team-hub'
    | 'blog-hub'
    | 'legal-static'
    | 'utility';
  /**
   * For /legal/licensing/{state}/.
   */
  legalState?: (number | null) | State;
  lede?: string | null;
  layout?:
    | (
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Mono label above the heading. Two or three words.
             */
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            /**
             * Numbered in the order shown here. Drag to reorder; the numbers follow.
             */
            items?:
              | {
                  title: string;
                  body: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'steps';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            body?: string | null;
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * Text comes from ComplianceSettings; a page never carries its own copy of a disclosure.
             */
            key: 'independentAgency' | 'medicareTpmo' | 'stateLicensing';
            id?: string | null;
            blockName?: string | null;
            blockType: 'disclosure';
          }
        | {
            form: number | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
      )[]
    | null;
  /**
   * Leave blank to derive from the document. Title ≤ 60, description ≤ 155.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Only an admin can set reviewed. Everything else renders noindex.
   */
  reviewStatus: 'draft' | 'in-review' | 'reviewed';
  /**
   * Stamped when reviewStatus first becomes reviewed. Shown as "Last reviewed" and cited in Article JSON-LD.
   */
  reviewedAt?: string | null;
  /**
   * Promoted by changing this, not by rebuilding.
   */
  indexWave: '1' | '2' | '3';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  name: string;
  /**
   * Derived from name when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  leadType: 'contact' | 'intake' | 'medication' | 'quote' | 'referral';
  /**
   * Medication and health indications: shorter retention, admin-only read, never emailed in full.
   */
  collectsHealthInformation?: boolean | null;
  fields: {
    name: string;
    label: string;
    type:
      'text' | 'email' | 'tel' | 'date' | 'textarea' | 'select' | 'checkbox' | 'checkbox-group' | 'address' | 'hidden';
    required?: boolean | null;
    /**
     * WHATWG autocomplete token, e.g. given-name, tel, bday
     */
    autocomplete?: string | null;
    inputmode?: string | null;
    /**
     * Stored only in Leads.data, never in notifications or logs.
     */
    pii?: boolean | null;
    placeholder?: string | null;
    help?: string | null;
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Populate options from the reviewed product list at render time.
     */
    optionsFromProducts?: boolean | null;
    id?: string | null;
  }[];
  submitLabel: string;
  /**
   * Shown after a successful submission.
   */
  confirmation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Notification recipients. Falls back to OWNER_EMAIL. Notifications never include PII fields.
   */
  notifyEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers".
 */
export interface Carrier {
  id: number;
  name: string;
  /**
   * Derived from name when blank. Lowercase, hyphens, no apostrophes.
   */
  slug: string;
  active?: boolean | null;
  /**
   * Date the appointment under Desert Peak Insurance was confirmed in writing.
   */
  appointmentConfirmedAt: string;
  logo?: (number | null) | Media;
  website?: string | null;
  lines?: (number | Product)[] | null;
  states?: (number | State)[] | null;
  /**
   * Internal; never rendered.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Path only, with leading and trailing slash.
   */
  from: string;
  /**
   * Path or absolute URL. Empty for 410.
   */
  to?: string | null;
  statusCode: '301' | '410';
  source: 'legacy-crawl' | 'slug-change' | 'manual';
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  reference?: string | null;
  form?: (number | null) | Form;
  type: 'contact' | 'intake' | 'medication' | 'quote' | 'referral';
  status: 'new' | 'contacted' | 'qualified' | 'quoted' | 'bound' | 'closed' | 'rejected';
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  interest?: (number | Product)[] | null;
  assignedAgent?: (number | null) | Agent;
  containsHealthInformation?: boolean | null;
  /**
   * The raw submission. Admin-only. Purged with the lead.
   */
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Attribution. IP is stored hashed with REFERRAL_HASH_SALT, never raw.
   */
  source?: {
    page?: string | null;
    referralCode?: string | null;
    utm?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    ipHash?: string | null;
    userAgent?: string | null;
  };
  /**
   * Agent notes. No health information here.
   */
  notes?: string | null;
  retainUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-sessions".
 */
export interface QuoteSession {
  id: number;
  token: string;
  step: number;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rum-samples".
 */
export interface RumSample {
  id: number;
  metric: 'CLS' | 'INP' | 'LCP' | 'TTFB' | 'FCP';
  value: number;
  rating: 'good' | 'needs-improvement' | 'poor';
  path: string;
  navigationType?: string | null;
  device?: ('mobile' | 'desktop') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-programs".
 */
export interface ReferralProgram {
  id: number;
  tenant: number | Tenant;
  name: string;
  /**
   * customer = unlicensed individuals (nominal-gift regime); partner = licensed producers and business partners. Separate rule sets, ledgers and portals. Never collapsed.
   */
  track: 'customer' | 'partner';
  /**
   * Ships false.
   */
  active: boolean;
  activeFrom?: string | null;
  activeTo?: string | null;
  /**
   * A qualified referral is a real, consenting, non-duplicate person who was contacted. The engine enforces opt-in and contact; a bound policy is not, and cannot be made, a condition.
   */
  qualification?: {
    /**
     * Tenant-specific wording for the portal; not a rule.
     */
    note?: string | null;
  };
  /**
   * Requested reward. The rule row for the referee's state and this track caps it; the engine takes the lower.
   */
  reward?: {
    type?: ('gift-card' | 'merchandise' | 'account-credit' | 'none') | null;
    amount?: number | null;
  };
  /**
   * Versioned. Acceptance is recorded against a version; editing a version in place is refused.
   */
  terms?:
    | {
        version: string;
        effectiveFrom: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  currentTermsVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-reward-rules".
 */
export interface ReferralRewardRule {
  id: number;
  label?: string | null;
  tenant: number | Tenant;
  /**
   * Two-letter state code (matches the referee's state).
   */
  stateAbbr: string;
  track: 'customer' | 'partner';
  /**
   * Applies to Medicare-touching referrals (CMS: nominal, non-cash, never an enrollment incentive).
   */
  medicareRuleSet: boolean;
  /**
   * null = engine refuses
   */
  rewardTypeAllowed?: ('gift-card' | 'merchandise' | 'account-credit' | 'none') | null;
  /**
   * null = engine refuses
   */
  perReferralCap?: number | null;
  /**
   * null = engine refuses
   */
  perReferrerAnnualCap?: number | null;
  /**
   * null = engine refuses
   */
  cashEquivalentAllowed?: ('yes' | 'no') | null;
  /**
   * Statute, regulation or bulletin with URL. null = engine refuses.
   */
  sourceCitation?: string | null;
  verifiedBy?: string | null;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrers".
 */
export interface Referrer {
  id: number;
  tenant: number | Tenant;
  /**
   * Short, unambiguous (no 0/O/1/I/L). Unique per tenant.
   */
  code?: string | null;
  track: 'customer' | 'partner';
  /**
   * A new referrer's first reward waits in the manual review queue until an admin activates them.
   */
  status: 'pending-review' | 'active' | 'suspended';
  /**
   * Partner track: the portal login.
   */
  user?: (number | null) | User;
  name: string;
  email: string;
  phone?: string | null;
  emailNormalized?: string | null;
  phoneNormalized?: string | null;
  addressNormalized?: string | null;
  termsAcceptance?: {
    program?: (number | null) | ReferralProgram;
    version?: string | null;
    acceptedAt?: string | null;
    ipHash?: string | null;
  };
  /**
   * Abstracted. Never a card or account number.
   */
  payoutMethod?: ('gift-card-email' | 'check-by-mail' | 'account-credit' | 'none') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: number;
  tenant: number | Tenant;
  program: number | ReferralProgram;
  referrer: number | Referrer;
  referee: {
    firstName: string;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    /**
     * Decides which reward rule row applies.
     */
    stateAbbr?: string | null;
    emailNormalized?: string | null;
    phoneNormalized?: string | null;
  };
  interest?: (number | Product)[] | null;
  /**
   * Set from interest. Routes to the Medicare rule set.
   */
  medicareTouching: boolean;
  source: 'link' | 'code' | 'form' | 'portal';
  attribution?: {
    code?: string | null;
    model?: 'first-touch' | null;
    firstTouchAt?: string | null;
    landingPage?: string | null;
  };
  consent: {
    /**
     * The referrer affirmed they have the referee's permission. Required to create a referral.
     */
    referrerAffirmedPermission: boolean;
    /**
     * Exactly one, ever.
     */
    optInMessagesSent: number;
    optInSentAt?: string | null;
    optInStatus: 'pending' | 'accepted' | 'declined' | 'expired';
    optInRespondedAt?: string | null;
    optInToken?: string | null;
  };
  status: 'submitted' | 'contacted' | 'qualified' | 'quoted' | 'bound' | 'closed' | 'rejected';
  rejectionReason?:
    | (
        | 'self-referral'
        | 'duplicate-referee'
        | 'disposable-email'
        | 'velocity-referrer'
        | 'velocity-ip'
        | 'bot-check-failed'
        | 'consent-not-affirmed'
        | 'referee-declined'
        | 'referee-no-response'
        | 'manual'
      )
    | null;
  duplicateOf?: (number | null) | Referral;
  /**
   * Every rejection has a reason code; nothing is dropped silently.
   */
  fraud?: {
    selfReferral?: boolean | null;
    duplicateReferee?: boolean | null;
    disposableEmail?: boolean | null;
    velocity?: boolean | null;
    botCheckPassed?: boolean | null;
    /**
     * First reward for a new referrer waits here.
     */
    manualReview?: boolean | null;
  };
  /**
   * Created only after the referee opts in.
   */
  lead?: (number | null) | Lead;
  ipHash?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-ledger".
 */
export interface RewardLedger {
  id: number;
  tenant: number | Tenant;
  referrer: number | Referrer;
  referral: number | Referral;
  type: 'earned' | 'issued' | 'reversed';
  /**
   * For reversed entries: voiding an earned reward, or clawing back an issued one.
   */
  reversesType?: ('earned' | 'issued') | null;
  rewardType: 'gift-card' | 'merchandise' | 'account-credit' | 'none';
  amount: number;
  currency: string;
  /**
   * The rule row as it stood when this entry was written.
   */
  ruleSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  termsVersion: string;
  actor:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason?: string | null;
  reverses?: (number | null) | RewardLedger;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-events".
 */
export interface ReferralEvent {
  id: number;
  tenant: number | Tenant;
  referral?: (number | null) | Referral;
  referrer?: (number | null) | Referrer;
  /**
   * status-change | rejected | reward-earned | reward-refused | reward-issued | reward-reversed | opt-in-sent | opt-in-response | created
   */
  type: string;
  from?: string | null;
  to?: string | null;
  actor:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipHash?: string | null;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-templates".
 */
export interface MessageTemplate {
  id: number;
  tenant: number | Tenant;
  key: 'referee-opt-in' | 'referrer-welcome';
  version: number;
  active: boolean;
  subject: string;
  /**
   * Placeholders: {{referrerFirstName}} {{refereeFirstName}} {{agencyName}} {{acceptUrl}} {{declineUrl}}. The opt-in message must name the referrer and let the referee decline.
   */
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'states';
        value: number | State;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'location-overrides';
        value: number | LocationOverride;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'glossary-terms';
        value: number | GlossaryTerm;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'agents';
        value: number | Agent;
      } | null)
    | ({
        relationTo: 'carriers';
        value: number | Carrier;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'quote-sessions';
        value: number | QuoteSession;
      } | null)
    | ({
        relationTo: 'rum-samples';
        value: number | RumSample;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'referral-programs';
        value: number | ReferralProgram;
      } | null)
    | ({
        relationTo: 'referral-reward-rules';
        value: number | ReferralRewardRule;
      } | null)
    | ({
        relationTo: 'referrers';
        value: number | Referrer;
      } | null)
    | ({
        relationTo: 'referrals';
        value: number | Referral;
      } | null)
    | ({
        relationTo: 'reward-ledger';
        value: number | RewardLedger;
      } | null)
    | ({
        relationTo: 'referral-events';
        value: number | ReferralEvent;
      } | null)
    | ({
        relationTo: 'message-templates';
        value: number | MessageTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tier?: T;
  category?: T;
  thirdSubpage?: T;
  parent?: T;
  medicareTouching?: T;
  summary?: T;
  intro?: T;
  coverageBlocks?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  covered?:
    | T
    | {
        item?: T;
        id?: T;
      };
  notCovered?:
    | T
    | {
        item?: T;
        id?: T;
      };
  discounts?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedProducts?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  reviewStatus?: T;
  reviewedAt?: T;
  indexWave?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "states_select".
 */
export interface StatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  abbr?: T;
  licenseNumber?: T;
  doi?:
    | T
    | {
        name?: T;
        url?: T;
      };
  statutoryMinimums?:
    | T
    | {
        product?: T;
        coverage?: T;
        requirement?: T;
        sourceUrl?: T;
        verifiedAt?: T;
        note?: T;
        id?: T;
      };
  riskNotes?: T;
  notableRegulatory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  state?: T;
  sizeBand?: T;
  cityFacts?:
    | T
    | {
        county?: T;
        nearestOfficeOrAgent?: T;
        localHazards?: T;
        housingStock?: T;
        drivingContext?: T;
        neighborhoods?:
          | T
          | {
              name?: T;
              id?: T;
            };
        notableRegulatory?: T;
      };
  intro?: T;
  factsComplete?: T;
  factsMissing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "location-overrides_select".
 */
export interface LocationOverridesSelect<T extends boolean = true> {
  label?: T;
  product?: T;
  city?: T;
  intro?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        attribution?: T;
        consentOnFile?: T;
        consentDocument?: T;
      };
  assignedAgent?: T;
  customFaqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  section?: T;
  excerpt?: T;
  body?: T;
  relatedProducts?: T;
  relatedArticles?: T;
  relatedStates?: T;
  relatedTerms?: T;
  wordCount?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  reviewStatus?: T;
  reviewedAt?: T;
  indexWave?: T;
  generation?:
    | T
    | {
        status?: T;
        generatedAt?: T;
        batch?: T;
        error?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary-terms_select".
 */
export interface GlossaryTermsSelect<T extends boolean = true> {
  term?: T;
  slug?: T;
  definition?: T;
  inPractice?: T;
  example?: T;
  relatedTerms?: T;
  relatedProducts?: T;
  wordCount?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  reviewStatus?: T;
  reviewedAt?: T;
  indexWave?: T;
  generation?:
    | T
    | {
        status?: T;
        generatedAt?: T;
        batch?: T;
        error?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  noindex?: T;
  path?: T;
  template?: T;
  legalState?: T;
  lede?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        disclosure?:
          | T
          | {
              key?: T;
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              form?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  reviewStatus?: T;
  reviewedAt?: T;
  indexWave?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  active?: T;
  user?: T;
  title?: T;
  bio?: T;
  photo?:
    | T
    | {
        image?: T;
        releaseOnFile?: T;
      };
  licenses?:
    | T
    | {
        state?: T;
        licenseNumber?: T;
        npn?: T;
        id?: T;
      };
  citiesServed?: T;
  products?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carriers_select".
 */
export interface CarriersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  active?: T;
  appointmentConfirmedAt?: T;
  logo?: T;
  website?: T;
  lines?: T;
  states?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        content?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  source?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  leadType?: T;
  collectsHealthInformation?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        required?: T;
        autocomplete?: T;
        inputmode?: T;
        pii?: T;
        placeholder?: T;
        help?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        optionsFromProducts?: T;
        id?: T;
      };
  submitLabel?: T;
  confirmation?: T;
  notifyEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  reference?: T;
  form?: T;
  type?: T;
  status?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  interest?: T;
  assignedAgent?: T;
  containsHealthInformation?: T;
  data?: T;
  source?:
    | T
    | {
        page?: T;
        referralCode?: T;
        utm?: T;
        ipHash?: T;
        userAgent?: T;
      };
  notes?: T;
  retainUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-sessions_select".
 */
export interface QuoteSessionsSelect<T extends boolean = true> {
  token?: T;
  step?: T;
  data?: T;
  expiresAt?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rum-samples_select".
 */
export interface RumSamplesSelect<T extends boolean = true> {
  metric?: T;
  value?: T;
  rating?: T;
  path?: T;
  navigationType?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  referralsEnabled?: T;
  agencyDisplayName?: T;
  notifyEmail?: T;
  velocity?:
    | T
    | {
        perReferrerPerDay?: T;
        perIpPerHour?: T;
      };
  dedupeWindowDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-programs_select".
 */
export interface ReferralProgramsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  track?: T;
  active?: T;
  activeFrom?: T;
  activeTo?: T;
  qualification?:
    | T
    | {
        note?: T;
      };
  reward?:
    | T
    | {
        type?: T;
        amount?: T;
      };
  terms?:
    | T
    | {
        version?: T;
        effectiveFrom?: T;
        text?: T;
        id?: T;
      };
  currentTermsVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-reward-rules_select".
 */
export interface ReferralRewardRulesSelect<T extends boolean = true> {
  label?: T;
  tenant?: T;
  stateAbbr?: T;
  track?: T;
  medicareRuleSet?: T;
  rewardTypeAllowed?: T;
  perReferralCap?: T;
  perReferrerAnnualCap?: T;
  cashEquivalentAllowed?: T;
  sourceCitation?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrers_select".
 */
export interface ReferrersSelect<T extends boolean = true> {
  tenant?: T;
  code?: T;
  track?: T;
  status?: T;
  user?: T;
  name?: T;
  email?: T;
  phone?: T;
  emailNormalized?: T;
  phoneNormalized?: T;
  addressNormalized?: T;
  termsAcceptance?:
    | T
    | {
        program?: T;
        version?: T;
        acceptedAt?: T;
        ipHash?: T;
      };
  payoutMethod?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  tenant?: T;
  program?: T;
  referrer?: T;
  referee?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        stateAbbr?: T;
        emailNormalized?: T;
        phoneNormalized?: T;
      };
  interest?: T;
  medicareTouching?: T;
  source?: T;
  attribution?:
    | T
    | {
        code?: T;
        model?: T;
        firstTouchAt?: T;
        landingPage?: T;
      };
  consent?:
    | T
    | {
        referrerAffirmedPermission?: T;
        optInMessagesSent?: T;
        optInSentAt?: T;
        optInStatus?: T;
        optInRespondedAt?: T;
        optInToken?: T;
      };
  status?: T;
  rejectionReason?: T;
  duplicateOf?: T;
  fraud?:
    | T
    | {
        selfReferral?: T;
        duplicateReferee?: T;
        disposableEmail?: T;
        velocity?: T;
        botCheckPassed?: T;
        manualReview?: T;
      };
  lead?: T;
  ipHash?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reward-ledger_select".
 */
export interface RewardLedgerSelect<T extends boolean = true> {
  tenant?: T;
  referrer?: T;
  referral?: T;
  type?: T;
  reversesType?: T;
  rewardType?: T;
  amount?: T;
  currency?: T;
  ruleSnapshot?: T;
  termsVersion?: T;
  actor?: T;
  reason?: T;
  reverses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-events_select".
 */
export interface ReferralEventsSelect<T extends boolean = true> {
  tenant?: T;
  referral?: T;
  referrer?: T;
  type?: T;
  from?: T;
  to?: T;
  actor?: T;
  ipHash?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-templates_select".
 */
export interface MessageTemplatesSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  version?: T;
  active?: T;
  subject?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName?: string | null;
  /**
   * Display form, e.g. 801-300-9980
   */
  phone?: string | null;
  /**
   * tel: form, digits only, e.g. tel:8013009980
   */
  phoneHref?: string | null;
  email?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: (number | null) | State;
    zip?: string | null;
  };
  officeHours?: string | null;
  /**
   * Indexation: documents in this wave and below are indexable once reviewed. Promotion is this field, not a deploy. Criteria in SEO-PLAYBOOK.md.
   */
  promotedWave: '1' | '2' | '3';
  /**
   * The advisor panel in the homepage hero. The photo is optional; the panel holds without one.
   */
  advisor?: {
    name?: string | null;
    title?: string | null;
    /**
     * One sentence, in the advisor's voice.
     */
    statement?: string | null;
    photo?: (number | null) | Media;
  };
  /**
   * The carrier strip under the hero. Names are text until the client supplies licensed logo files (TODO-CLIENT-DATA.md).
   */
  carriers?: {
    /**
     * e.g. "Appointed with 40+ carriers"
     */
    headline?: string | null;
    names?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Written consent from every quoted client is on file. Until this is checked, the testimonial section does not render anywhere, whatever is entered below.
   */
  testimonialConsentConfirmed?: boolean | null;
  /**
   * Real, named, consented. The date is the date of the written consent.
   */
  testimonials?:
    | {
        quote: string;
        name: string;
        consentDate: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    /**
     * Google Business Profile URL
     */
    google?: string | null;
  };
  nav?: {
    header?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    footer?:
      | {
          heading: string;
          links?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  defaultSeo?: {
    titleSuffix?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Admin only. Every page reads disclosures from here; nothing is duplicated on a page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-settings".
 */
export interface ComplianceSetting {
  id: number;
  independentAgencyDisclosure: string;
  /**
   * docs/RECONCILIATION.md: yes. When true, every Medicare-touching page must render the TPMO disclaimer.
   */
  medicareInScope?: boolean | null;
  /**
   * Plan-year approved text. TODO token until supplied (TODO-CLIENT-DATA.md #11).
   */
  medicareTpmoDisclaimer?: string | null;
  /**
   * e.g. 2027
   */
  medicarePlanYear?: string | null;
  /**
   * Template. {{licenseNumber}} and {{state}} are substituted from States.
   */
  stateLicensingDisclosure?: string | null;
  /**
   * Do not display a state count until the client confirms the list (TODO-CLIENT-DATA.md #1).
   */
  licensedStatesNote?: string | null;
  /**
   * The build fails on any hit in rendered text (page-generation Phase 4).
   */
  bannedPhrases?:
    | {
        phrase: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leads without health information. 24 months by default; counsel may change it.
   */
  leadRetentionDays: number;
  /**
   * Leads with medication or health indications. 12 months by default.
   */
  healthLeadRetentionDays: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
      };
  officeHours?: T;
  promotedWave?: T;
  advisor?:
    | T
    | {
        name?: T;
        title?: T;
        statement?: T;
        photo?: T;
      };
  carriers?:
    | T
    | {
        headline?: T;
        names?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  testimonialConsentConfirmed?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        consentDate?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        google?: T;
      };
  nav?:
    | T
    | {
        header?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        footer?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  defaultSeo?:
    | T
    | {
        titleSuffix?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-settings_select".
 */
export interface ComplianceSettingsSelect<T extends boolean = true> {
  independentAgencyDisclosure?: T;
  medicareInScope?: T;
  medicareTpmoDisclaimer?: T;
  medicarePlanYear?: T;
  stateLicensingDisclosure?: T;
  licensedStatesNote?: T;
  bannedPhrases?:
    | T
    | {
        phrase?: T;
        id?: T;
      };
  leadRetentionDays?: T;
  healthLeadRetentionDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}